# Generated by Django 5.1.15 on 2026-05-23 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plugin_deploymentplan_deploymentnode_auditlog_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deploymentnode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='deploymentjob',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.plugin'),
        ),
        migrations.AddConstraint(
            model_name='deploymentnode',
            constraint=models.UniqueConstraint(fields=('plan', 'target_id'), name='uq_plan_target'),
        ),
    ]
